# 数据源配置
jdbc:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3366/biticket?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true
                username: root
                password: 123456
#                url: jdbc:mysql://rm-j6cfa46tnd83b26uqdo.mysql.rds.aliyuncs.com:3366/jinguo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true
#                username: kingoadmin
#                password: KingoApp_C()nn2018Go
             # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url:
                username:
                password:
                # 初始连接数
                initial-size: 10
                # 最大连接池数量
                max-active: 100
                # 最小连接池数量
                min-idle: 10
                # 配置获取连接等待超时的时间
                max-wait: 60000
                # 打开PSCache，并且指定每个连接上PSCache的大小
                pool-prepared-statements: true
                max-pool-prepared-statement-per-connection-size: 20
                # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
                timeBetweenEvictionRunsMillis: 60000
                # 配置一个连接在池中最小生存的时间，单位是毫秒
                min-evictable-idle-time-millis: 300000
                validation-query: SELECT 1 FROM DUAL
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false
                stat-view-servlet:
                    enabled: true
                    url-pattern: /monitor/druid/*
                filter:
                    stat:
                        log-slow-sql: true
                        slow-sql-millis: 1000
                        merge-sql: false
                    wall:
                        config:
                        multi-statement-allow: true
 # 项目相关配置
biticket:
  #名称
  #name: RuoYi
  name: BicketApi
  #版本
  version: 1.1.0
  #版权年份
  copyrightYear: 2018
  #头像上传路径
  profile: ${upload.path}
  # 获取ip地址开关
  addressEnabled: true
#开发环境配置
server:
  #服务端口
  port: 9190
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
#日志配置
logging:
  level:
    com.biticket: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
#用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
#Spring配置
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  messages:
    #国际化资源文件路径
    basename: config/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  #文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  devtools:
    restart:
      #热部署开关
      enabled: true
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.biticket.project
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:config/mybatis-config.xml
# PageHelper
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
# Shiro
#shiro:
#  user:
#    # 登录地址
#    loginUrl: /login
#    # 权限认证失败地址
#    unauthorizedUrl: /unauth
#    # 首页地址
#    indexUrl: /index
#    # 验证码开关
#    captchaEnabled: true
#    # 验证码类型 math 数组计算 char 字符
#    captchaType: math
#  cookie:
#    # 设置Cookie的域名 默认空，即当前访问的域名
#    domain:
#    # 设置cookie的有效访问路径
#    path: /
#    # 设置HttpOnly属性
#    httpOnly: true
#    # 设置Cookie的过期时间，天为单位
#    maxAge: 30
#  session:
#    # Session超时时间（默认30分钟）
#    expireTime: 30
#    # 同步session到数据库的周期（默认1分钟）
#    dbSyncPeriod: 1
#    # 相隔多久检查一次session的有效性，默认就是10分钟
#    validationInterval: 10
# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*,/login
  # 匹配链接
  urlPatterns: /wallet/*,/monitor/*,/tool/*

# 短信
sms.yy:
    url: https://dx.ipyy.net/sms.aspx
    signature: 金果商城
    appKey: AA00086
    appSecrect: AA0008613
    isOpen: false

# 阿里短信网关
sms.dayu:
     product: Dysmsapi
     domain: dysmsapi.aliyuncs.com
     appKey: LTAIStZhSHI83t37
     appSecret: XY4HERHGmX12A2t6UhG7RzTF16BPoj
     isOpen: true